### ISSUE TITLE
backporter_build_mirror: 'http://cdn.debian.net/debian' DNS doesn't resolve ipv6

### ISSUE THREAD

**Issue by Mboyer** [debops/ansible-backporter#4]
The /etc/apt/sources.list.d/http_debian_net_debian.list is causing issues with apt as it can't be resolved via ipv6:

Traceback (most recent call last):
  File "/home/remote/.ansible/tmp/ansible-tmp-1425397474.99-160979525085496/apt_repository", line 2508, in <module>
    main()
  File "/home/remote/.ansible/tmp/ansible-tmp-1425397474.99-160979525085496/apt_repository", line 436, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 418, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://cdn.debian.net/debian/dists/wheezy/main/source/Sources  404  Not Found [IP: 2001:41c8:1000:21::21:35 80]
, W:Failed to fetch http://cdn.debian.net/debian/dists/wheezy/contrib/source/Sources  404  Not Found [IP: 2001:41c8:1000:21::21:35 80]
, E:Some index files failed to download. They have been ignored, or old ones used instead.

backporter_build_mirror: 'http://http.debian.net/debian' does work after the cdn file has been removed.

**Comment by drybjed** [comment]
The default server should be changed. Will do that when I have the chance.

**Comment by drybjed** [comment]
The `debops.backporter` role has been deprecated. I'm closing this issue.
